language: clojure
lein: 2.7.0
jdk:
    - oraclejdk8
addons:
  firefox: "49.0"
before_script:
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - while [ ! -e /tmp/.X11-unix/X99 ]; do sleep 2; done
script:
  - lein test-refresh :run-once
  - lein doo firefox automated-tests once
